service

diff --git a/0x0E-web_stack_debugging_1/1-debugging_made_short b/0x0E-web_stack_debugging_1/1-debugging_made_short
--- a/0x0E-web_stack_debugging_1/1-debugging_made_short
+++ b/0x0E-web_stack_debugging_1/1-debugging_made_short
@@ -4,6 +4,18 @@
 apt-get update
 apt-get install -y net-tools
 systemctl start nginx
-netstat -lnt | grep ":80 " || sed -i '/listen 80 default_server;/c\    listen 80 default_server;' /etc/nginx/sites-available/default && systemctl reload nginx
-curl -sI 0:80 | grep "200 OK" && echo "Nginx is running on port 80." || echo "Error: Nginx is not running on port 80."
 
+if ! netstat -lnt | grep ":80 "; then
+  sed -i '/listen 80 default_server;/c\    listen 80 default_server;' /etc/nginx/sites-available/default
+  systemctl reload nginx
+fi
+
+if ! curl -sI 0:80 | grep "200 OK"
+then
+  echo "Error: Nginx is not running on port 80."
+fi
+
+if ! service nginx status | grep "not running"
+then
+  echo "service (init) says that nginx is not running."
+fi
